### ISSUE TITLE
Resultados: datos estación

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#10]
- Falta una gráfica (más fácil de comprender que la tabla) antes de la tabla.
- Faltan las unidades en los nombres de las columnas.
- La columna de fecha debe reflejar exclusivamente el día (sobra la hora).
- Sobran decimales (es suficiente con una o dos cifras).

**Comment by Gonmeso** [comment]
Resuelto en el commit "Issue 10 Fix"
