### ISSUE TITLE
Resultados: radiación en el plano horizontal y del generador

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#11]
- Las unidades son incorrectas: son valores de irradiación (densidad de energía) y por tanto debe ser Wh/m2.
- La gráfica debe ir antes que la tabla.
- Sobran decimales (basta 1 o 2).

**Comment by Gonmeso** [comment]
Resuelto en el commit "Issue 11 Fix"
