### ISSUE TITLE
Resultados: energía producida

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#13]
- La tensión es irrelevante. No debe aparecer ni en las tablas ni en la gráfica. En cualquier caso, sus unidades son V, no kV.
- En la tabla faltan resultados de energía (atención a las unidades).
- Falta una gráfica de productividad, y debe ir antes de las tablas.
- Sobran decimales (basta 1 o 2).

**Comment by Gonmeso** [comment]
Solucionado en el commit "Issue 13 fix" además se ha colocado la gráfica de energía antes de las tablas, tal y como se encontraba en los apartados anteriores
