### ISSUE TITLE
Resultados: resumen

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#14]
En Valores medios:
- Las unidades son incorrectas.
- Sobran decimales.
- Faltan gráficas.
¿Realmente hacen falta aquí? Creo que en esta sección basta con los datos del sistema. Es más, esta sección debiera ir antes, situada entre Datos Estación y Radiación en el plano horizontal.

**Comment by Gonmeso** [comment]
Solucionado en el commit "Issue 14 & 15 Fix"
