### ISSUE TITLE
Orientación e inclinación en sistema estático

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#18]
Al seleccionar modo de seguimiento "estático" se debe poder definir la orientación (alfa) e inclinación (beta) del generador, usando por defecto los valores óptimos.

**Comment by Gonmeso** [comment]
Añadido en el commit "Issue 18 Fix"

**Comment by oscarperpinan** [comment]
Los selectores aparecen también para "eje horizontal" y "doble eje"
