### ISSUE TITLE
Diagramas erróneos

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#20]
- En el apartado Introducción > Componentes del Sistema se usa un diagrama de un sistema fotovoltaico autónomo.
- En el apartado Componentes > Inversores no se muestra la figura.

**Comment by Gonmeso** [comment]
Arreglado en el commit  "Issue 20 Fix"

**Comment by oscarperpinan** [comment]
Los diagramas no se ven en ninguno de los dos casos.

**Comment by Gonmeso** [comment]
Al lanzar la aplicación a mi se me muestran perfectamente. Adjunto una imagen de lo que veo al lanzar la aplicación 
![image](https://cloud.githubusercontent.com/assets/18899187/21901052/7cd6e1b8-d8f6-11e6-91d1-509e6774ff6a.png)

Edit: La figura se encuentra en el repositorio -> https://github.com/Gonmeso/Fotovoltaica_101/blob/master/www/EsquemaSFCR.jpg
