### ISSUE TITLE
Explicación de datos de radiación solar

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#21]
- En Diseño > Geometría solar no se explica cómo se obtienen los datos de radiación.
- Creo que este apartado se debería renombrar a radiación solar.

**Comment by Gonmeso** [comment]
Añadido en "Issue 21 Fix". Se han añadido definiciones de las distintas radiaciones, creo que para un usuario normal la obtención de las radiaciones puede ser un poco densa.
