### ISSUE TITLE
Selección de paneles

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#22]
En Diseño > Paneles y células hay un selector que ofrece diferentes paneles, pero no queda clara la razón de los valores que se obtienen en cada caso.

**Comment by Gonmeso** [comment]
No entiendo muy bien esta Issue, si pudieras aclararme un poco de que se trata lo arreglo lo antes posible.

**Comment by oscarperpinan** [comment]
Cuando seleccionas módulo monocristalino algunos parámetros toman un valor. Al seleccionar módulo policristalino esos mismos parámetros cambian (otros permanecen constantes). Es normal que cambien, pero no tengo claro el origen de esos valores. ¿Vienen de fichas técnicas? ¿Son estimaciones? Es pregunta típica de tribunal :smirk:

**Comment by Gonmeso** [comment]
He añadido un pequeño recuadro en el que se indica que estas provienen de fichas técnicas proporcionadas por el fabricante. Dejo la issue abierta hasta tu revisión.

**Comment by oscarperpinan** [comment]
Ok, ahora se entiende bien. 

Falta corregir el funcionamiento cuando seleccionas célula de silicio amorfo.
