### ISSUE TITLE
Selección de inversores

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#24]
- En Diseño > Inversores hay un selector que ofrece diferentes inversores. Los valores de los coeficientes k de la curva de eficiencia no cambian. Eso debiera mejorarse o al menos explicarse.
- Se debe poder elegir más de un inversor (del mismo modelo).

**Comment by Gonmeso** [comment]
Solucionado en el commit "Issue 24 Fix", Incluida descripción de los datos, selección del número de inversores y salida de los datos de los inversores
