### ISSUE TITLE
Coherencia en la selección de inversores y generador

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#25]
En diseño se puede elegir de forma independiente el tamaño del generador (número de módulos en serie y paralelo) y el inversor. El usuario puede elegir un generador mucho más grande que el inversor sin que pase nada. La aplicación debería, al menos, advertir cuando la relación de potencias sea demasiado alta o demasiado baja.

**Comment by Gonmeso** [comment]
Creado un popUp de aviso se el dimensionamiento no es correcto. Commit "Issue 25 Fix"

**Comment by oscarperpinan** [comment]
La condición no es correcta. En la [página 86 de mi libro](http://oscarperpinan.github.io/esf/ESF.pdf#page=86) explico la relación entre potencia de generador y de inversor.

**Comment by Gonmeso** [comment]
He incluido una condición para que el sobredimensionamiento no sea mayor del 40%, si pensabas hacerlo según la curva del inversor, las fichas técnicas de los inversores que encontré no aparecía la curva, por lo que no puede obtener los datos de los coeficientes y se suelen utilizar aquellos por defecto.
Dejo la issue abierta a la espera de tu respuesta

**Comment by oscarperpinan** [comment]
Comentarios varios para mejorar este tema:
- Tanto en el apartado del generador como en el del inversor, se debe mostrar la potencia respectiva. Es más, en los datos del módulo no aparece este valor, y es importante que se muestre.
- En lugar de que aparezca una ventana (que son, en general, molestas), es mejor en mi opinión que añadas un texto tanto en el apartado de generador como de inversor indicando el valor del ratio Pg*/Pinv para que el usuario tenga un contexto y pueda decidir.
- Algo similar falta con las tensiones y corrientes. Es lo que se explica en la [sección 6.3.2 Configuración eléctrica del generador](http://oscarperpinan.github.io/esf/ESF.pdf#page83). Por ejemplo, prueba a elegir el módulo "Mitsubishi PV-MJE275FB" con Ns = 12, Np = 11, y el inversor por defecto. Verás que `fProd` entrega un warning, y que los valores de productividad son muy extraños.

**Comment by Gonmeso** [comment]
En un commit he resuelto las dos primeras, en cuanto a la tercera observo que el Vmpp dentro de fProd se realizan ciertas operaciones para su cálculo,  El Vmpp puedo sacarlo tras realizar los cálculos (mal si no cumple el Vmpp min) y ya recomendar un número de módulos, mientras que antes de calcular no puedo hacer una recomendación fiable, pues esta puede variar en varios módulos, por lo tanto no es lo óptimo.  ¿Es mejor solo mostrar la recomendación una vez se ha realizado un cálculo? ¿ O hay alguna manera de obtener Vmpp min antes de obtener los datos de radiación y temperatura?

**Comment by oscarperpinan** [comment]
Las cifras del factor de dimensionado, potencia del generador, etc. aparecen en unos "widgets" que aparentan ser modificables. Sin embargo, son cifras de "sólo lectura". Por tanto, debes usar un `renderText` o similar.

> ¿ O hay alguna manera de obtener Vmpp min antes de obtener los datos de radiación y temperatura?

Te recomendé la lectura de la sección 6.3.2. Ahí viene descrito el procedimiento. Verás que en las ecuaciones 6.12 a 6.16 no se necesitan datos de radiación ni temperatura. En el apéndice C verás varios ejercicios de diseño resueltos  por si te surgen dudas.

**Comment by Gonmeso** [comment]
Buenas Oscar, sigo intentando implementar este punto, pero no consigo entenderlo muy bien. según entiendo la ecuación 6.15, debería de poder obtener el numero minimo de modules dividiendo el Vmin de inversor ente Vmpp, que en este caso sería e valor nominal en condiciones estándar, poniendolo en numeros, el Vmin del inversor por defecto es 420 y el Vmn del módulo por defecto es 46.08,  con lo que haciendo la división nos daría 9.11 -> 10 módulos, donde si usamos este valor saldría el error mencionado hasta poner 12 en serie. Entonces no se si me estoy equivocando (seguramente) o puede ser por otra cosa.

**Comment by oscarperpinan** [comment]
> dividiendo el Vmin de inversor ente Vmpp, que en este caso sería e valor nominal en condiciones estándar

Fíjate bien en las ecuaciones: todas están particularizadas para una determinada radiación y temperatura. En el caso de la ecuación 6.15 el cálculo es para G = 1000 W/m^2 y **Ta** = 25ºC. Recuerda que las condiciones STC son para **Tc** = 25ºC. Es decir, no es la tensión nominal sino la Vmpp corregida con la temperatura. Nuevamente te recomiendo que leas los ejercicios del apéndice.  Por ejemplo, el apartado 2 del ejercicio C.1.2. resuelve precisamente este tema.
