### ISSUE TITLE
Tablas en resumen del sistema

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#26]
Los datos del sistema (Resultados > Resumen del sistema) se muestran en tablas usando `DataTable`. Es innecesario porque son tablas de una sola fila (ocupa más el armazón de `DataTable` que el propio contenido). Es suficiente con `renderTable` y `tableOutput`.

**Comment by Gonmeso** [comment]
Cambio aplicado en el commit "Issue 26 Fix"
