### ISSUE TITLE
Unidades en resultados

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#27]
- La productividad se refleja habitualmente en kWh/kWp (en lugar de Wh/Wp).
- Cuando las cifras son del orden de miles o superior es conveniente usar kWh en lugar de Wh (facilita la comprensión de los valores).
- El 2 en m^2 debería estar correctamente representado con un superíndice.

**Comment by Gonmeso** [comment]
Solucionado parcialmente en "Issue 27 Parcial Fix 1", la productividad se muestra según lo indicado, los valores de potencia se muestran en kW incluida la gráfica.
Falta solucionar mostrar el exponente

**Comment by oscarperpinan** [comment]
La productividad aparece sin unidades.
