### ISSUE TITLE
Valores mensuales

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#30]
Las tablas de valores medios mensuales deben mostrar directamente 12 filas correspondientes a los meses del año.

**Comment by oscarperpinan** [comment]
Falta añadir una gráfica, similar a la de valores diarios.

**Comment by Gonmeso** [comment]
Estoy intentando mantener el tema de las gráficas pèro no consigo mantenerlo, he utilizado funciones del tipo as.ZooM, pero no consigo dejar xyplot con el mismo estilo. Me queda de la siguiente manera:
![image](https://cloud.githubusercontent.com/assets/18899187/22218768/979fcffe-e1a8-11e6-93f5-0783137f4c89.png)

**Comment by oscarperpinan** [comment]
Así es suficiente.
