### ISSUE TITLE
Datos de estación

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#32]
En el apartado Resultados > Datos Estación no se indica la latitud/longitud del punto elegido, ni tampoco las estaciones de SIAR empleadas para obtener valores de radiación.

**Comment by Gonmeso** [comment]
![image](https://cloud.githubusercontent.com/assets/18899187/22034014/10c4efda-dceb-11e6-9228-ec03e347cedf.png)
  Al seleccionar cualquier punto me aparecen los datos correctamente. Aqui se muestran los cambios del commit, pero comento para añadir la captura.

**Comment by oscarperpinan** [comment]
Acabo de comprobar con la última versión y las estaciones siguen sin aparecer.

**Comment by Gonmeso** [comment]
Hola Oscar, ejecutando la aplicación en local me funciona perfectamente, incluso al lanzarlo desde shinyapps se muestran en la aplicación dentro del navegador, por lo que no me explico que puede estar pasando. Si necesitas puedo lanzarte la aplicación desde shinyapps pra que lo compruebes, pero a mi por ahora me funciona correctamente.

**Comment by oscarperpinan** [comment]
Vaya, no entiendo. Sí, por favor, dime la URL de shinyapps y pruebo ahí.

**Comment by Gonmeso** [comment]
Aquí está la URL https://fotovoltaica101.shinyapps.io/fotovoltaica_101/

**Comment by Gonmeso** [comment]
Idem Issue #34
