### ISSUE TITLE
Error de ejecución al cambiar de localidad

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#34]
He probado varias veces lo siguiente: elijo un punto  en el mapa, y después de que el programa ejecute los cálculos, vuelvo al mapa y elijo otro punto diferente. A la segunda o tercera vez de hacer esto la aplicación se interrumpe con este mensaje:

```
Warning: Error in if: argumento tiene longitud cero
Stack trace (innermost first):
    80: <reactive:dataEstacion> [/home/oscar/github/TFG_gonzalo/Fotovoltaica_101/server.R#297]
    69: dataEstacion
    68: <reactive:horizontalPlane> [/home/oscar/github/TFG_gonzalo/Fotovoltaica_101/server.R#514]
    57: horizontalPlane
    56: observerFunc [/home/oscar/github/TFG_gonzalo/Fotovoltaica_101/server.R#419]
     1: runApp
Warning: Error in if: argumento tiene longitud cero
Stack trace (innermost first):
    64: <Anonymous>
    63: stop
    62: horizontalPlane
    61: isTruthy [/home/oscar/github/TFG_gonzalo/Fotovoltaica_101/server.R#357]
    60: need
    59: lapply [/home/oscar/github/TFG_gonzalo/Fotovoltaica_101/server.R#357]
    58: sapply
    57: validate
    56: observerFunc [/home/oscar/github/TFG_gonzalo/Fotovoltaica_101/server.R#357]
     1: runApp

```

**Comment by Gonmeso** [comment]
Hola Oscar, lo siento pero no consigo reproducir el error, veo que uno se trata en la linea de un if, donde se comprueba que horizontalPLane no sea Null, esto una vez se ha calculado debería de dar TRUE siempre, aún así lo dicho, no consigo reproducirlo

**Comment by Gonmeso** [comment]
Según me has comentado, al no producirse esto error en la aplicación mediante shinyApps, consideramos que no se produce, por lo tanto cierro la Issue.
