### ISSUE TITLE
Cálculo realizado de forma repetida innecesariamente

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#35]
Una vez que se elige la localidad la aplicación realiza los cálculos 3 veces de manera innecesaria.

**Comment by Gonmeso** [comment]
He localizado el error, es producido por la función dailyMove con la que obtengo lo ángulos de la inclinación y la orientación, provoca que se actualicen los ángulos dentro de las funciones. Por lo que una vez ejecutado un cálculo, al clicar en otra localización actualiza los valores de los ángulos de la función antigua.

Sigo trabajando en ello.
