### ISSUE TITLE
SFCR: baterías e inversores

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#7]
La aplicación está dedicada exclusivamente a los Sistemas Fotovoltaicos de Conexión a Red (SFCR). Por tanto en Introducción > Componentes del Sistema y en el apartado Componentes:
- No tiene sentido mencionar a la batería
- Se debe usar un diagrama unifilar de un SFCR (el que hay corresponde a un sistema autónomo).
- Se debe explicar bien el funcionamiento del inversor, especificando que se trata de un inversor de conexión a red. Así, el texto siguiente es erróneo y debe ser eliminado:

>  Para mantener la fuente de energía estable, los inversores se conectan a baterías de manera que pueda suministrarse la energía uniformemente, además el inversor es el encargado de controlar cuando es necesario obtener energía de la batería, mantenerla o cargarla de la forma más óptima, con el fin de aprovechar la energía de la forma más favorable. En el caso de no estar conectado a una batería, el inversor proporcionará solo la energía que sea segura para la red, evitando así peligros para los sistemas conectados a esta.

**Comment by Gonmeso** [comment]
Solucionada en el commit "Issue 7 fix"
