### ISSUE TITLE
Ubicación de los textos explicativos

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#8]
En el apartado Diseño se incluyen en primer lugar los textos explicativos, de forma que los diálogos de elección de la localización, módulos, etc. quedan escondidos al final. La organización debe ser diferente, de forma que el usuario de la aplicación vea en primer lugar y con claridad los cuadros de selección y después, si lo desea, puede leer el texto.

**Comment by Gonmeso** [comment]
Solucionado en commit "Issue 8 Fix"
