### ISSUE TITLE
Selección de coordenadas

### ISSUE THREAD

**Issue by oscarperpinan** [Gonmeso/Fotovoltaica_101#9]
En línea con lo indicado en la issue #5, al seleccionar un punto del mapa no queda claro lo que ha pasado. Sería más comprensible para el usuario que los valores de los selectores "Longitud" y "Latitud" cambien su valor al de las coordenadas del punto elegido (están a cero siempre).

**Comment by Gonmeso** [comment]
Solucionado en el commit "Issue 9 Fix"
